---
title: Making better ACF and PACF plots using highcharter
author: ''
date: '2018-10-26'
slug: acf-and-pacf-highcharter
categories:
  - R
tags:
  - R
  - highcharts
  - time series
  - interactive plots
image:
  caption: 'Test'
  focal_point: ''
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r libraries}
library(highcharter)
library(forecast)
library(astsa)
library(ggplot2)
library(strucchange)
library(grid)
library(gridExtra)
library(widgetframe)
```

```{r acf highchart, results = 'asis'}
frameWidget(hchart(acf(diff(AirPassengers), plot = FALSE)))
```

And we can do the same with the partial correlation function

```{r pacf highchart, results = 'asis'}
frameWidget(hchart(pacf(diff(AirPassengers), plot = FALSE)))
```

But there are somethings that just aren't right about these plots. For example, the x-axis is off on the amount of lags, and, if we wanted to see both plots together, we wouldn't be able to. So this is my solution:

```{r acf and pacf highchart}
acf.ts <- acf(diff(AirPassengers), plot = F)
pacf.ts <- pacf(diff(AirPassengers), plot = F)
n <- acf.ts$n.used
l <- list()
l1 <- list()

for(i in 1:nrow(acf.ts$acf)) {
  l[[i]] <- list(x = i, y = acf.ts$acf[, , 1][i])
  l1[[i]] <- list(x = i, y = pacf.ts$acf[, , 1][i])
}

frameWidget(highchart() %>% 
  hc_title(text = "Gráfico de autocorrelaciones") %>% 
  hc_yAxis(title = list(text = "ACF"),
           plotLines = list(
             list(
               width = 1,
               value = qnorm((1 + 0.95) / 2) / sqrt(n),
               color = "gray"
           ), 
             list(
               width = 1,
               value = -qnorm((1 + 0.95) / 2) / sqrt(n),
               color = "gray"
             
           ))) %>% 
  hc_xAxis(title = list(text = "Rezagos")) %>% 
  hc_yAxis_multiples(
    create_yaxis(2, height = c(1, 1))
  ) %>% 
  hc_add_series(data = l,
            type = "column",
            pointWidth = 2,
            name = "ACF",
            yAxis = 0) %>% 
  hc_add_series(data = l1,
            type = "column",
            pointWidth = 2,
            name = "PACF",
            yAxis = 1))
```


{{% alert warning %}}
Here's some important information...
{{% /alert %}}

{{% alert note %}}
Here's a tip or note...
{{% /alert %}}